.TH KEEPASSXC-P11-WRAPPER "1" "April 2022" "User Commands"
.SH NAME
keepassxc-p11-wrapper - PKCS#11 wrapper for keepassxc
.SH DESCRIPTION
keepassxc-p11-wrapper can be used to open Keepass2 databases encrypted with the Keepass2 CertKeyProvider from
https://github.com/markbott/CertKeyProvider.
.SH OPTIONS
.HP
\fB\-debug\fR
.IP
enable debug output
.HP
\fB\-slot\fR int
.IP
use the given key slot
.SH "SEE ALSO"
The full documentation can be found at /usr/share/doc/keepassxc-pkcs11-wrapper/README.md.
